version: 8
preset: psr12
tab-width: 4
finder:
  exclude:
    - "bootstrap"
    - "build"
    - "config"
    - "node_modules"
    - "public"
    - "resources"
    - "routes"
    - "specs"
    - "storage"
    - "tests"
    - "vendor"
