os: linux

matrix:
  include:
    - language: php

      php:
        - 8.0

      addons:
        chrome: stable

      services: postgresql

      before_install:
        - createdb tortle_test

      install:
        - nvm use 12.18.1
        - cp .env.dusk.testing .env
        - travis_retry composer install --no-interaction --prefer-dist --no-suggest
        - php artisan key:generate
        - php artisan dusk:chrome-driver
        - yarn install

      before_script:
        - php artisan migrate
        - yarn dev
        - mkdir build
        - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
        - php artisan serve --no-reload &

      script:
        - php vendor/bin/phpunit
        - php artisan dusk

      after_success:
        - travis_retry php vendor/bin/php-coveralls -v

    - language: node_js

      node_js:
        - 14.16

      install:
        - yarn install
        - yarn dev

      script:
        - yarn lint
        - yarn test

